{
 "title": "SDKV Dashboard",
 "description": "Dashboard for SDKV",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "JVM Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   },
   { "name": "verticle_address", "label": "Verticle address", "query": { "query": "label_values(address)" } }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "CPU Usage - System",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "CPU Usage - JVM Process",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Average CPU Usage [15m] - JVM Process",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])"
    }
   ]
  },
  {
   "title": "Available System CPUs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of SDKV Vert.x nodes (hosts)",
   "type": "stat",
   "description": "The number of running SDKV instances in whole cluster",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(instance) (vertx_eventbus_handlers))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total stored SDKV object replicas",
   "type": "stat",
   "description": "The number of stored objects in the specified SDKV node",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(sdkv_stored_objects_gauge)" }
   ]
  },
  {
   "title": "SDKV per storage node metrics -- Host: {{$instance}} Verticle(s):  {{$verticle_address}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Stored SDKV objects",
   "type": "stat",
   "description": "The number of stored objects in the specified SDKV node",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_stored_objects_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\"})"
    }
   ]
  },
  {
   "title": "Total SDKV costs",
   "type": "stat",
   "description": "The total costs of SDKV so far. Note that the cost only increases after each billing period.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bill_total_cost_since_start_counter_total{instance=~\"$instance\", verticle_id=~\"$verticle_address\"})"
    }
   ]
  },
  {
   "title": "Latest SDKV Bill -- Host: {{$instance}} Verticle(s):  {{$verticle_address}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Unit active KV  price",
   "type": "stat",
   "description": "The unit active KV price of the latest bill",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdkv_bill_unit_active_kv_price_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\"})"
    }
   ]
  },
  {
   "title": "Unit storage price",
   "type": "stat",
   "description": "The unit storage price of the latest bill",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdkv_bill_unit_storage_price_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\"})",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Unit request prices",
   "type": "stat",
   "description": "The unit request prices of the latest bill",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdkv_bill_unit_request_price_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\"}) by(request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Unit EGRESS transfer prices ",
   "type": "stat",
   "description": "The unit  prices for egress data transfer of the latest bill",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdkv_bill_unit_transfer_price_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"unit_egress_transfer_price\"}) by(otherEnd)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Unit INGRESS transfer prices ",
   "type": "stat",
   "description": "The unit  prices for ingress data transfer of the latest bill",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sdkv_bill_unit_transfer_price_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"unit_ingress_transfer_price\"}) by(otherEnd)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "TCP request counts",
   "type": "stat",
   "description": "The total number of TCP requests in the latest billing period",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_request_count_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"tcp_number_of_requests\"}) by(request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "RPC request counts",
   "type": "stat",
   "description": "The total number of RPC requests in the latest billing period",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_request_count_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"rpc_number_of_requests\"}) by(request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Stored bytes",
   "type": "stat",
   "description": "The total stored bytes in the latest billing period",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_storage_bytes_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\"})",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "RPC data transfer IN",
   "type": "stat",
   "description": "The total ingress RPC data transfer in the latest billing period",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_data_transfer_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"rpc_transfer_in\"}) by(otherEnd)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "RPC data transfer OUT",
   "type": "stat",
   "description": "The total egress RPC data transfer in the latest billing period",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_data_transfer_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"rpc_transfer_out\"}) by(otherEnd)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Active KV millis",
   "type": "stat",
   "description": "The total execution time of all active KV invocations in the latest billing period",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_active_kv_millis_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\"})",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "TCP data transfer OUT",
   "type": "stat",
   "description": "The total egress TCP data transfer in the latest billing period",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_data_transfer_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"tcp_transfer_out\"}) by(otherEnd)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "TCP data transfer IN",
   "type": "stat",
   "description": "The total ingress TCP data transfer in the latest billing period",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sdkv_bill_data_transfer_gauge{instance=~\"$instance\", verticle_id=~\"$verticle_address\", category=\"tcp_transfer_in\"}) by(otherEnd)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Total Vertx Metrics (Aggregated)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Eventbus: sent rate total",
   "type": "timeseries",
   "description": "Total sent rates over all nodes and eventbuses",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": " {{sdkv_hostname}}"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_sent_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: received rate total",
   "type": "timeseries",
   "description": "Total sent rates over all nodes and eventbuses",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_eventbus_received_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: total pending on remote side",
   "type": "timeseries",
   "description": "Total number of messages not processed yet on remote side of any of the eventbusses in the cluster.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vertx_eventbus_pending{side=\"remote\"})",
     "legendFormat": "total pending messages"
    }
   ]
  },
  {
   "title": "Eventbus: pending on local side",
   "type": "timeseries",
   "description": "Number of messages not processed yet on local side of the specified verticle.",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vertx_eventbus_pending{side=\"local\", instance=~\"$instance\", address=~\"$verticle_address\"}",
     "legendFormat": "total pending messages - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    }
   ]
  },
  {
   "title": "NetServer: sent rate total",
   "type": "timeseries",
   "description": "Total number of bytes sent by the Net Servers of the cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_net_server_bytes_written_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_net_server_bytes_written_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_net_server_bytes_written_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "NetServer: received rate total",
   "type": "timeseries",
   "description": "Total number of bytes received by the Net Servers of the cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_net_server_bytes_read_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_net_server_bytes_read_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_net_server_bytes_read_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "NetServer: errors total",
   "type": "timeseries",
   "description": "Total number of errors that occurred in any of the Net Servers of the cluster.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(vertx_net_server_errors_total[1m]))",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "sum(rate(vertx_net_server_errors_total[1m]))",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "sum(rate(vertx_net_server_errors_total[5m]))",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: total pending on local side",
   "type": "timeseries",
   "description": "Total number of messages not processed yet on local side of any of the eventbusses in the cluster.",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vertx_eventbus_pending{side=\"local\"})",
     "legendFormat": "total pending messages"
    }
   ]
  },
  {
   "title": "Eventbus: number of handlers total",
   "type": "stat",
   "description": "Total number of eventbus handlers in the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vertx_eventbus_handlers)" }
   ]
  },
  {
   "title": "NetServer: total number of open connections",
   "type": "stat",
   "description": "Total number of open connections to NetServers",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vertx_net_server_active_connections)"
    }
   ]
  },
  {
   "title": "Individual Vertx Metrics Host: {{$instance}} Verticle(s): {{$verticle_address}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "Eventbus: sent rate",
   "type": "timeseries",
   "description": "Sent rates of specified SDKV node and Eventbus address",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(vertx_eventbus_sent_total{instance=~\"$instance\", address=~\"$verticle_address\"}[1m])",
     "legendFormat": "1 minute instant rate - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    },
    {
     "expr": "rate(vertx_eventbus_sent_total{instance=~\"$instance\", address=~\"$verticle_address\"}[1m])",
     "legendFormat": "1 minute rate - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    },
    {
     "expr": "rate(vertx_eventbus_sent_total{instance=~\"$instance\", address=~\"$verticle_address\"}[5m])",
     "legendFormat": "5 minute instant rate - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: received rate",
   "type": "timeseries",
   "description": "Received rates of specified SDKV node and Eventbus address",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(vertx_eventbus_received_total{instance=~\"$instance\", address=~\"$verticle_address\"}[1m])",
     "legendFormat": "1 minute instant rate - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    },
    {
     "expr": "rate(vertx_eventbus_received_total{instance=~\"$instance\", address=~\"$verticle_address\"}[1m])",
     "legendFormat": "1 minute rate - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    },
    {
     "expr": "rate(vertx_eventbus_received_total{instance=~\"$instance\", address=~\"$verticle_address\"}[5m])",
     "legendFormat": "5 minute instant rate - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    }
   ]
  },
  {
   "title": "Eventbus: pending on remote side",
   "type": "timeseries",
   "description": "Number of messages not processed yet on remote side of the specified verticle.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vertx_eventbus_pending{side=\"remote\", instance=~\"$instance\", address=~\"$verticle_address\"}",
     "legendFormat": "total pending messages - Host: {{sdkv_hostname}}, Event bus address: {{address}}"
    }
   ]
  },
  {
   "title": "NetServer: number of open connections",
   "type": "stat",
   "description": "Number of open connections to specified NetServer ",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vertx_net_server_active_connections{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "NetServer: sent rate",
   "type": "timeseries",
   "description": "Number of bytes sent by the specified Net Servers.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(vertx_net_server_bytes_written_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "1 minute instant rate - Host: {{sdkv_hostname}}, local: {{local}}, remote: {{remote}}"
    },
    {
     "expr": "rate(vertx_net_server_bytes_written_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "1 minute rate - Host: {{sdkv_hostname}}, local: {{local}}, remote: {{remote}}"
    },
    {
     "expr": "rate(vertx_net_server_bytes_written_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "5 minute rate - Host: {{sdkv_hostname}}, local: {{local}}, remote: {{remote}}"
    }
   ]
  },
  {
   "title": "NetServer: received rate",
   "type": "timeseries",
   "description": "Number of bytes received by the specified Net Servers.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(vertx_net_server_bytes_read_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "1 minute instant rate - Host: {{sdkv_hostname}}, local: {{local}}, remote: {{remote}}"
    },
    {
     "expr": "rate(vertx_net_server_bytes_read_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "1 minute rate - Host: {{sdkv_hostname}}, local: {{local}}, remote: {{remote}}"
    },
    {
     "expr": "rate(vertx_net_server_bytes_read_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "5 minute rate - Host: {{sdkv_hostname}}, local: {{local}}, remote: {{remote}}"
    }
   ]
  },
  {
   "title": "NetServer: errors",
   "type": "timeseries",
   "description": "Number of errors that occurred in the specified Net Server.",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(vertx_net_server_errors_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "1 minute instant rate"
    },
    {
     "expr": "rate(vertx_net_server_errors_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "1 minute rate"
    },
    {
     "expr": "rate(vertx_net_server_errors_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "5 minute rate"
    }
   ]
  },
  {
   "title": "Eventbus: number of handlers total",
   "type": "stat",
   "description": "Total number of eventbus handlers in the cluster",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vertx_eventbus_handlers{instance=~\"$instance\", address=~\"$verticle_address\"}",
     "legendFormat": "{{sdkv_hostname}}:{{address}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "description": "Information about Heap memory of the JVM",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "description": "Information about Non-Heap memory of the JVM",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "description": "Information about the total JVM memory (Heap + Non-Heap)",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Information about CPU usage",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "process-15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Information about total load in the system vs. total number of cores",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
     "legendFormat": "CPU time spent on GC"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "description": "Information about threads in different states",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Information about number of threads",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "repeat": "persistence_counts",
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 126 },
   "repeat": "jvm_memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 134 },
   "repeat": "jvm_memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 148 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "description": "Number of currently loaded classes in JVM",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "description": "Difference in number of loaded classes ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=\"$application\",instance=\"$instance\"}[1m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$jvm_buffer_pool",
   "type": "timeseries",
   "description": "Used bytes of the given JVM buffer pool, \nBytes capacity of the given JVM buffer pool, \nand number of buffers used of the given buffer pool",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
   "repeat": "jvm_buffer_pool",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_count_buffers{application=\"$application\", instance=\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  }
 ]
}